<h2>List Items</h2>
<?php if (count($this->records)): ?>
    <div id="pager" style="text-align: center">
        Pages: <?php echo $this->pages; ?>
    </div>
    <div id="records">
        <form method="post" action="<?php echo $this->url(array(), 'admin-catalog-delete'); ?>">
            <table>
                <tr>
                    <td colspan="3" style="text-align: center">
                        <input type="submit" name="submit" style="width:150px" value="Delete Selected"/>
                    </td>
                    <td colspan="6" style="text-align: center">
                        <a href="<?php echo $this->url(array(), 'admin-fulltext-index-create'); ?>">
                            Update full-text indexices
                        </a>
                    </td>
                </tr>
                <tr style="text-align: center">
                    <td></td>
                    <td class="key" width="110px">
                        Item ID
                        <a href="<?php echo $this->url(array('sort' => 'RecordID', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a>
                        <a href="<?php echo $this->url(array('sort' => 'RecordID', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>
                    </td>
                    <td class="key" width="*">
                        Title
                        <a href="<?php echo $this->url(array('sort' => 'Title', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a>
                        <a href="<?php echo $this->url(array('sort' => 'Title', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>
                    </td>
                    <td class="key" width="160px">
                        Denomination
                        <a href="<?php echo $this->url(array('sort' => 'Denomination', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a>
                        <a href="<?php echo $this->url(array('sort' => 'Denomination', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>
                    </td>
                    <td class="key" width="110px">
                        Country
                        <a href="<?php echo $this->url(array('sort' => 'CountryID', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a>
                        <a href="<?php echo $this->url(array('sort' => 'CountryID', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>
                    </td>
                    <td class="key" width="90px">
                        Grade
                        <a href="<?php echo $this->url(array('sort' => 'GradeID', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a>
                        <a href="<?php echo $this->url(array('sort' => 'GradeID', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>
                    </td>
                    <td class="key" width="80px">
                        Year
                        <a href="<?php echo $this->url(array('sort' => 'Year', 'dir' => 'asc'), 'admin-catalog-index'); ?>">&uArr;</a>
                        <a href="<?php echo $this->url(array('sort' => 'Year', 'dir' => 'desc'), 'admin-catalog-index'); ?>">&dArr;</a>
                    </td>
                    <td></td>
                    <td></td>
                </tr>
                <?php foreach ($this->records as $r): ?>
                    <tr>
                        <td><input type="checkbox" name="ids[]" value="<?php echo $r['RecordID']; ?>"
                                   style="width:2px"/></td>
                        <td style="text-align: center"><?php echo $this->escape($r['RecordID']); ?></td>
                        <td>
                            <a href="<?php echo $this->url(array('id' => $this->escape($r['RecordID'])), 'catalog-display'); ?>"
                               target="_blank">
                                <?php echo $this->escape($r['Title']); ?>
                            </a>
                            </td>
                        <td style="text-align: right"><?php echo $this->escape(sprintf('%1.2f', $r['Denomination'])); ?></td>
                        <td><?php echo $this->escape($r['Zf1_Model_Country']['CountryName']); ?></td>
                        <td style="text-align: center"><?php echo $this->escape($r['Zf1_Model_Grade']['GradeName']); ?></td>
                        <td style="text-align: center"><?php echo $this->escape($r['Year']); ?></td>
                        <td><a href="<?php echo $this->url(array('id' => $r['RecordID']), 'admin-catalog-display'); ?>">Display</a>
                        </td>
                        <td><a href="<?php echo $this->url(array('id' => $r['RecordID']), 'admin-catalog-update'); ?>">Update</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </form>
    </div>

    <div id="pager" style="text-align: center">
        Pages: <?php echo $this->pages; ?>
    </div>

<?php else: ?>
    No records found
<?php endif; ?>
