<?php
// create XML document
$dom = new DOMDocument('1.0', 'utf-8');

// create root element
$root = $dom->createElementNS('http://zf1.demo', 'zf1:document');
$dom->appendChild($root);

// convert to SimpleXML
$xml = simplexml_import_dom($dom);

// add summary element
$xml->addChild('matches', count($this->results));
$xml->addChild('searchTime', time());

// add resultset elements
$results = $xml->addChild('results');
foreach ($this->results as $r) {
  $result = $results->addChild('result');
  $result->addChild('score', $this->escape($r->score));
  $result->addChild('id', $this->escape($r->RecordID));
  $result->addChild('title', $this->escape($r->Title));
  $result->addChild('year', $this->escape($r->Year));
  $result->addChild('grade', $this->escape($r->Grade));
  $result->addChild('country', $this->escape($r->Country));
  $price = $result->addChild('price');
  $price->addChild('min', $this->escape($r->SalePriceMin));
  $price->addChild('max', $this->escape($r->SalePriceMax));
}

// return output
echo $xml->asXML();
?>
